results_table = array2table(results,...
    'VariableNames', { ...
    'NA',...
    'Wavelength_nm',...
    'Distance (m)',...
    'Lval_um',...
    'Zone calcul', ...
    'RoC_mm',...
    'FinalPower',...
    'db/m',...
    'PowerAfterInsertion'});

%% -------------------------------
%% 💾 Save file
%% -------------------------------

csvfile = fullfile(folderName,[folderName '_data.csv']);
writetable(results_table,csvfile)


fprintf('\n✅ Sweep complete → %s\n', folderName);

elapsedTime = toc(sweepTimer);
fprintf('⏱️ Total time: %.2f seconds\n', elapsedTime);
